### ISSUE TITLE
Syncing from Zurg/Rclone to Symlink Library

### ISSUE THREAD

**Issue by idanlah** [rivenmedia/riven#800]
Is it possible to create symlinks in riven for all media currently in zurg?
i want to start using riven but i don't want to add each item and re-scrape it just to get the symlink.
is it possible to run some script that will create all symlinks to media already present in zurg?

also, it can also be helpful if symlinks could be created automatically when a new media file is available in rclone/zurg. this way its decoupling the scraping and downloading from the symlinking (sometimes downloading is not done using riven)

**Comment by dreulavelle** [comment]
Nope.

**Comment by dreulavelle** [comment]
We already symlink automatically once an item is downloaded on Riven. As for the other question, we can't symlink raw torrents because we don't know what they are. 

We match metadata to items and that's how we know what to look for and ensure accuracy. We don't blindly download our symlink random torrents.
